version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - app_data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/healthz"]

volumes:
  app_data: